name: yuki-no

on:
  # Allow manual trigger (Optional)
  workflow_dispatch:

jobs:
  yuki-no:
    name: Yuki-no
    runs-on: ubuntu-latest
    steps:
      - uses: Gumball12/yuki-no@v1
        with:
          # GitHub access token. Required.
          access-token: ${{ secrets.GITHUB_TOKEN }}

          # Git user name to use when making issues. Optional.
          # Defaults to 'github-actions'.
          # Note: Using only one of username or email might cause
          # GitHub Actions bot to work incorrectly.
          username: github-actions

          # Git email address to use when making issues. Optional.
          # Defaults to 'action@github.com'.
          # Note: Using only one of username or email might cause
          # GitHub Actions bot to work incorrectly.
          email: 'action@github.com'

          # The url for the upstream repo. This is the repository that you
          # set up Yuki-no. Required.
          upstream-repo: https://github.com/vitejs/docs-ko.git

          # The head repo to track. This is the repository you want to
          # take a diff. Required.
          head-repo: https://github.com/vitejs/vite.git

          # The branch for the head repo. Optional.
          # Defaults to 'main'.
          head-repo-branch: main

          # The git commit sha of head repo to start tracking. Yuki-no will
          # only track commit from this hash. Required.
          track-from: 4ed8b2f83a2f149734f3c5ecb6438309bd85a9e5

          # File path to track. If specified, Yuki-no will only track commits
          # that modified files under this path. If not specified, it will
          # track all files in the project root. Optional.
          path-starts-with: docs/

          # Labels to add to the issues. You can specify multiple labels.
          # Each label must be separated by a newline. Optional.
          # If empty string('') is provided, no labels will be added.
          # Defaults to 'sync'.
          labels: |
            sync
            needs review
            my-label

          # Whether to enable release tracking.
          # When enabled, Yuki-no will track releases for each issue
          # and add comments about release status. Optional.
          # Defaults to 'false'
          release-tracking: true
