name: yuki-no

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  yuki-no:
    name: Yuki-no
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Gumball12/yuki-no@v1
        with:
          # GitHub token for authentication (uses repository's token)
          access-token: ${{ secrets.GITHUB_TOKEN }}

          # Required: Git user info
          # Tip: Using github-actions bot credentials is recommended
          # as it clearly indicates that the issues are created by
          # an automated process
          username: github-actions
          email: 'action@github.com'

          # Required: Repository where issues will be created
          head-repo: https://github.com/your-org/your-repo.git

          # Required: Source repository to track changes from
          upstream-repo: https://github.com/original/repo.git

          # Optional: Source repository's branch (defaults to 'main')
          upstream-repo-branch: main

          # Optional: Only track changes in specific paths (defaults to project root)
          path-starts-with: docs/

          # Required: Initial commit to start tracking from
          initial-commit: 4ed8b2f83a2f149734f3c5ecb6438309bd85a9e5
